#!/bin/bash

rm /usr/share/applications/exo-mail-reader.desktop
rm /usr/share/applications/exo-terminal-emulator.desktop
rm /usr/share/applications/exo-web-browser.desktop
rm /usr/share/applications/Thunar-bulk-rename.desktop
rm /usr/share/applications/vim.desktop
rm /usr/share/applications/tint2.desktop
rm /usr/share/applications/volti.desktop
rm /usr/share/applications/Thunar.desktop
rm /usr/share/applications/xfce4-session-logout.desktop
rm /usr/share/applications/xfce4-screenshooter.desktop
rm /usr/share/applications/display-im6.q16.desktop

rm -r /usr/share/icons/Adwaita
rm -r /usr/share/themes/Adwaita
rm -r /usr/share/themes/Adwaita-dark
rm -r /usr/share/themes/Bright
rm -r /usr/share/themes/Daloa
rm -r /usr/share/themes/Emacs
rm -r /usr/share/themes/Kokodi
rm -r /usr/share/themes/Moheli
rm -r /usr/share/themes/Raleigh
rm -r /usr/share/themes/Retro
rm -r /usr/share/themes/Smoke
rm -r /usr/share/themes/ZOMG-PONIES!

cd /tmp
wget --no-check-certificate https://dxt2.co.za/download/dxt2.7z
7z e dxt2.7z
7z x -aoa share.7z -o/usr/share
7z x -aoa user.7z -o/etc/skel
7z x -aoa user.7z -o/root

for destdir in /home/*/; do
    7z x -aoa  user.7z -o"$destdir";
    chown 1000:1000 -R /home/*;
done

_user="$(id 1000 -u -n)"
sed -i "s/#autologin-user=/autologin-user=$_user/g" /etc/lightdm/lightdm.conf 

rm *.7z

cp apt.conf /etc/apt
rm apt.conf
cp lightdm-gtk-greeter.conf /etc/lightdm
rm lightdm-gtk-greeter.conf
cd /usr/share/dxt2
cat sysctl >> /etc/sysctl.conf

echo "export PATH=\"/usr/share/dxt2:\$PATH\"" >> /etc/skel/.bashrc

for destdir in /home/*/; do
    echo "export PATH=\"/usr/share/dxt2:\$PATH\"" >> "$destdir"/.bashrc
done

echo "export PATH=\"/usr/share/dxt2:\$PATH\"" >> /root/.bashrc

echo "DXT2" > /etc/hostname
echo "127.0.0.1	localhost" > /etc/hosts
echo "127.0.1.1	DXT2" >> /etc/hosts
echo "%sudo    ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

find /usr/share/locale -mindepth 1 -maxdepth 1 ! -name 'en*' -exec rm -r {} \;
find /usr/share/doc -depth -type f ! -name copyright -delete
rm -r /usr/share/doc/*
rm -r /usr/share/help/*
rm -r /usr/share/man/*
chsh -s /bin/bash root
chsh -s /bin/bash user

timedatectl set-local-rtc 1
systemctl disable rsyslog.service

/usr/share/dxt2/dxt2grub
/usr/share/dxt2/installtmp
/usr/share/dxt2/update

sync
