#!/bin/bash
rm -r /var/spool/bootcd
bootcdwrite -s
isohybrid /var/spool/bootcd/cdimage.iso
notify-send -t 0 "ISO located at /var/spool/bootcd/cdimage.iso"
notify-send -t 0 "Copy it somewhere as the tool clears the folder on every use"
exit
