#!/bin/bash
echo "Installing Office"
apt install -y libreoffice-calc libreoffice-impress libreoffice-writer
cp /usr/share/dxt2/apps/libreoffice-calc.desktop /usr/share/applications
cp /usr/share/dxt2/apps/libreoffice-impress.desktop /usr/share/applications
cp /usr/share/dxt2/apps/libreoffice-writer.desktop /usr/share/applications
rm /usr/share/applications/libreoffice-draw.desktop
rm /usr/share/applications/libreoffice-startcenter.desktop
echo ""
