#!/bin/bash

echo "Installing office software..."
echo ""
sleep 1
apt install -y libreoffice-calc libreoffice-impress libreoffice-writer
rm /usr/share/applications/libreoffice-draw.desktop
echo ""
sleep 2
notify-send "Office installed"
exit
