#!/bin/bash
echo "Installing networking..."
apt install -y samba
printf "\n" | tee -a /etc/samba/smb.conf
echo "client max protocol = NT1" | tee -a /etc/samba/smb.conf
printf "\n" | tee -a /etc/samba/smb.conf
exit
