#!/bin/bash

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | apt-key add -
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | apt-key add -

apt update
apt install virtualbox-6.1
wget --no-check-certificate https://download.virtualbox.org/virtualbox/6.1.4/Oracle_VM_VirtualBox_Extension_Pack-6.1.4.vbox-extpack
yes | VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-6.1.4.vbox-extpack
cp /usr/share/dxt2/apps/virtualbox.desktop /usr/share/applications
apt install -y gcc g++ linux-headers-amd64 make perl
read -p "Username to add to vboxusers group: " vboxuser
adduser $vboxuser vboxusers
/sbin/vboxconfig

#Uninstall
#VBoxManage extpack uninstall "Oracle VM VirtualBox Extension Pack"
