#!/bin/bash

read -p "Upgrading to Pro... Reboots automatically." beginsetup
echo ""

apt install -y curl build-essential deluge deepin-picker filezilla font-manager gimp lxtask partclone radiotray rsync
cp /usr/share/dxt2/config.xml /home/*/.local/share/radiotray
cp /usr/share/dxt2/gimp.desktop /usr/share/applications
rm /usr/share/applications/org.gnome.FontManager.desktop

/usr/share/dxt2/installnetworking
/usr/share/dxt2/installprinting
/usr/share/dxt2/installsublime
/usr/share/dxt2/installteamviewer
/usr/share/dxt2/installtmp
/usr/share/dxt2/installvirtualbox
cp /usr/share/dxt2/virtualbox.desktop /usr/share/applications
echo ""

sync
reboot
