#!/bin/bash

apt install -y build-essential gcc g++ linux-headers-amd64 make perl

wget --no-check-certificate https://download.virtualbox.org/virtualbox/6.1.10/virtualbox-6.1_6.1.10-138449~Debian~buster_amd64.deb
dpkg -i virtualbox-6.1_6.1.10-138449~Debian~buster_amd64.deb ; apt install -f -y

wget --no-check-certificate https://download.virtualbox.org/virtualbox/6.1.10/Oracle_VM_VirtualBox_Extension_Pack-6.1.10.vbox-extpack
yes | VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-6.1.10.vbox-extpack

cp /usr/share/dxt2/apps/virtualbox.desktop /usr/share/applications
read -p "Enter username to add to vboxusers group: " vboxuseradd
adduser $vboxuseradd $vboxusers
/sbin/vboxconfig

rm Oracle_VM_VirtualBox_Extension_Pack-6.1.10.vbox-extpack
rm virtualbox-6.1_6.1.10-138449~Debian~buster_amd64.deb
